// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1IiH0Lt_tBLnyA2gsFpkPhiQk1GXzV-s',
    appId: '1:824461774798:web:9d44e9c0b924a93483259f',
    messagingSenderId: '824461774798',
    projectId: 'reddit-clone-1bf93',
    authDomain: 'reddit-clone-1bf93.firebaseapp.com',
    storageBucket: 'reddit-clone-1bf93.appspot.com',
    measurementId: 'G-DK17M6ZRSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9-l4kWySJgIPkt1ehtJxvTR61CzLyl_U',
    appId: '1:824461774798:android:4d9fddd02c00d3b783259f',
    messagingSenderId: '824461774798',
    projectId: 'reddit-clone-1bf93',
    storageBucket: 'reddit-clone-1bf93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_btTLRhjHNJCGylKQJcF8WFt4RCveB2U',
    appId: '1:824461774798:ios:43285a474f55cdec83259f',
    messagingSenderId: '824461774798',
    projectId: 'reddit-clone-1bf93',
    storageBucket: 'reddit-clone-1bf93.appspot.com',
    iosClientId: '824461774798-nh2bj7ni8rb066ljqt5l8sg6310ktb81.apps.googleusercontent.com',
    iosBundleId: 'wixforum.com.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_btTLRhjHNJCGylKQJcF8WFt4RCveB2U',
    appId: '1:824461774798:ios:43285a474f55cdec83259f',
    messagingSenderId: '824461774798',
    projectId: 'reddit-clone-1bf93',
    storageBucket: 'reddit-clone-1bf93.appspot.com',
    iosClientId: '824461774798-nh2bj7ni8rb066ljqt5l8sg6310ktb81.apps.googleusercontent.com',
    iosBundleId: 'wixforum.com.redditClone',
  );
}
